# Cambrian.jl settings
d_fitness: 1
n_population: 10
n_elite: 1
n_gen: 50
log_gen: 5
save_gen: 5
m_rate: 0.1
p_crossover: 0
# MTCGP.jl settings
rows: 2
columns: 200
out_m_rate: 0.3
functions:
  - f_add
  - f_subtract
  - f_mult
  - f_abs
  - f_exp
  - f_sin
  - f_lt
  - f_gt
