# Cambrian.jl settings
d_fitness: 1
n_population: 10
n_elite: 1
n_gen: 10000
log_gen: 1
save_gen: 1
m_rate: 0.1
p_crossover: 0
# CGP.jl settings
rows: 1
columns: 300
recur: 0.5
out_m_rate: 0.3
functions:
  - f_add
  - f_subtract
  - f_mult
  - f_div
  - f_abs
  - f_sqrt
  - f_pow
  - f_exp
  - f_sin
  - f_cos
  - f_tanh
  - f_sqrt_xy
  - f_lt
  - f_gt
