# NEAT agent settings
n_in: 5
n_out: 3
d_fitness: 2
innovation_max: 0
p_mut_weights: 0.1
weight_factor: 0.1
p_mut_neurons: 0.1
p_mutate_weights: 0.9
p_mutate_enabled: 0.0
p_mutate_add_neuron: 0.01
p_mutate_add_connection: 0.3

# Cambrian.jl settings
n_population: 1
n_elite: 1
n_gen: 2
log_gen: 5
save_gen: 5
m_rate: 0.1
p_crossover: 0
